version: "3.5"

services:
  api01: &api01
    build: .
    hostname: api01
    environment:
      DATABASE_URL: postgresql://rinha:rinha@db/rinha?connect_timeout=60
      DATABASE_MAX_POOL_SIZE: 100
      REDIS_MAX_POOL_SIZE: 200
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    expose:
      - "80"
    #network_mode: "host" notworking on wsl
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"

  api02:
    <<: *api01
    hostname: api02
    expose:
      - "80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"

  redis:
    image: redis:latest
    hostname: redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
