#======================POST 
POST http://localhost:9999/pessoas

{
    "apelido" : "josée",
    "nome" : "José Roberto",
    "nascimento" : "2000-10-01",
    "stack" : ["C#", "Node", "Oracle"]
}

###
POST http://localhost:9999/pessoas

{
    "apelido" : "anaa",
    "nome" : "Ana Barbosa",
    "nascimento" : "1985-09-23",
    "stack" : null
}

###
POST http://localhost:9999/pessoas

{
    "apelido" : "apelido",
    "nome" : "nome",
    "nascimento" : "1985-01-01",
    "stack" : [1, "PHP"]
}

###
GET http://localhost:9999/pessoas/20cb2dec-a4f1-11ee-a52c-abb21d424974


###
GET http://localhost:9999/pessoas?t=jo

###
GET http://localhost:9999/contagem-pessoas