name: ci

on:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: check java version
        run: java -version
      
      - name: clone rinha-backend
        run: |
          git clone https://github.com/zanfranceschi/rinha-de-backend-2023-q3.git --depth 1 $HOME/rinha-de-backend-2023-q3
        
      - name: donwload gatling
        run: |
          wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          mv gatling-charts-highcharts-bundle-3.9.5 $HOME/gatling/3.9.5
          rm gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          ls -la $HOME/gatling

      - name: FastAPI Stack
        run: |
          cd rinha-2023-fastapi && docker-compose up --build --detach && docker ps -a && sleep 10
          curl http://localhost:9999/contagem-pessoas -v
          echo "FastAPI Stack ready"
          echo "Starting stress test"
          cd $HOME/rinha-de-backend-2023-q3/stress-test && ./run-test.sh